name: Publish image to Docker Hub
on:
  push:
    branches:
      - master
    tags:
      - 20*
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/graphite-grafana
          tag_with_ref: true
          tag_with_sha: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

